# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aff84c651c287c368422bb973064ae8a57a5d29d3cb6b1e06d5843f88fcc25f3ab1c2038766df94e429bd40ebd59ada3a8a5a096b2ba11776c6a60185f1dbfe

test:
  secret_key_base: 23ea48a27479d88abb96b267a2a1f6ccee941ec36054a1b390a0b1c33a25e474f35b6a14f05647229dc2b81b94c041cd272b5e027814784091e11d5300e5f35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
